# Generated by Django 5.2.7 on 2025-10-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('ssd', models.IntegerField()),
                ('harddisk', models.IntegerField()),
                ('operating', models.CharField(max_length=255)),
                ('graphics', models.CharField(max_length=255)),
                ('screen', models.IntegerField()),
                ('resolution', models.CharField(max_length=255)),
                ('nocores', models.IntegerField()),
                ('nothreads', models.IntegerField()),
                ('specscore', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
