# Generated by Django 5.2.7 on 2025-10-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='imageurl',
            field=models.CharField(default='images\x07cer-one.png', max_length=255),
            preserve_default=False,
        ),
    ]
