# Generated by Django 5.2.7 on 2025-10-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_laptop_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='harddisk',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='operating',
        ),
    ]
