# Generated by Django 5.2.7 on 2025-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_laptop_harddisk_remove_laptop_operating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='screen',
            field=models.FloatField(),
        ),
    ]
